config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
  :registrations => 'users/registrations',
  :sessions => 'users/sessions'
}

devise_scope :user do
  root 'top#index'
  get "sign_in", :to => "users/sessions#new"
  get "sign_out", :to => "users/sessions#destroy"
  end

  get 'pages/show', to: 'pages#index'
  get 'top', to: 'top#index', as: :top
  get 'top/edit', to: 'top#edit', as: :top_edit
  post 'top/create', to: 'top#create', as: :top_create
  get 'top/list/:id', to: 'top#show', as: :top_show
  delete 'top/delete/:id', to: 'top#delete', as: :top_delete
  post 'list/create', to: 'list#create', as: :list_create
  get 'res/:id', to: 'list#show', as: :list_show
  delete 'list/:id/delete', to: 'list#delete', as: :list_delete
  post 'res/create', to: 'list#create_res', as: :list_create_res
  delete 'res/:id/delete/:id', to: 'list#delete_res', as: :list_delete_res
  #get 'top/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    #@tilte = 'THE 雑談'
    @boards = Board.all
    @newboards = Board.new
    @users = User.all
    #render template: 'top/index'
  end

  def show
    @boards = Board.find(params[:id])
    @newthres = Thre.new(:board_id => params[:id])
    @thres = Thre.where(board_id: params[:id])
  end

  def edit
    @newBoards = Board.new
  end

  def create
    #@boards = Board.new
    @boards = Board.new(params[:board].permit(:id, :user_id, :name, :is_delete))
    @boards.user_id = current_user.id
    if @boards.is_delete == nil
      @boards.is_delete = false
    end
    is_saved = @boards.save
    redirect_to top_path

  end

  def delete
    @boards = Board.find(params[:id])
    @boards.destroy
    redirect_to top_path
  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/top/create.html.erb
h1
  | トピック新規登録
= form_for @newBoards, :url => {:action => 'create'} do |f|
  = f.text_field :name
  = f.submit

app/views/top/edit.html.slim
h1
  | 新規登録
= form_for @newBoards, :url => top_create_path do |f|
  = f.text_field :name
  = f.submit

app/views/top/index.html.slim
doctype html
html
  head
    link[href="https://fonts.googleapis.com/css?family=Bitter:400,700|Pinyon+Script" rel="stylesheet"]
  body#top
    #wrap
      .content
        h1 
         | Culture Topic
        ul
          - @boards.each do |board|
            li
              = link_to board.name, top_show_path(board.id)
              - if user_signed_in? == true and current_user.admin == true then
                = link_to '[削除]', top_delete_path(board.id), method: :delete, data: {confirm: "削除してもよろしいですか？"}

- if user_signed_in? == true and current_user.admin == true then
  = link_to '板新規作成', top_edit_path

app/views/top/show.html.slim
h1= @boards.name
- @thres.each_with_index do |thre , idx|
  li
    = link_to thre.name, list_show_path(thre.id)
    - if user_signed_in? && thre.user_id == current_user.id then
      = link_to '[削除]', list_delete_path(thre.id), method: :delete, data: {confirm: "削除してもよろしいですか？"}


h3
  | スレッド作成
= form_for @newthres, :url => list_create_path do |f|
  p
  = f.text_field :name
  p
  = f.hidden_field :board_id
  = f.submit

= link_to 'Back', top_path