config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
  :registrations => 'users/registrations',
  :sessions => 'users/sessions'
}

devise_scope :user do
  root 'top#index'
  get "sign_in", :to => "users/sessions#new"
  get "sign_out", :to => "users/sessions#destroy"
  end

  get 'pages/show', to: 'pages#index'
  get 'top', to: 'top#index', as: :top
  get 'top/edit', to: 'top#edit', as: :top_edit
  post 'top/create', to: 'top#create', as: :top_create
  get 'top/list/:id', to: 'top#show', as: :top_show
  delete 'top/delete/:id', to: 'top#delete', as: :top_delete
  post 'list/create', to: 'list#create', as: :list_create
  get 'res/:id', to: 'list#show', as: :list_show
  delete 'list/:id/delete', to: 'list#delete', as: :list_delete
  post 'res/create', to: 'list#create_res', as: :list_create_res
  delete 'res/:id/delete/:id', to: 'list#delete_res', as: :list_delete_res
  #get 'top/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/list_controller.rb
class ListController < ApplicationController
  def create
    @thres = Thre.new(params[:thre].permit(:id, :name, :user_id, :board_id, :is_delete))
    if user_signed_in? == true then
      @thres.user_id = current_user.id
    else
      @thres.user_id = ""
    end

    if @thres.is_delete == nil then
      @thres.is_delete = false
    end
    @thres.save
    redirect_to top_show_path(params[:thre]['board_id'])
  end

  def show
    #@boards = Board.find(params[:id])
    @thres = Thre.find(params[:id])
    #@thres = Thre.where(board_id: params[:id])
    @newresponses = Response.new(:thre_id => params[:id])
    #@newresponses = Response.new(params[:response].permit(:id, :thre_id, :content, :user_id, :user_name, :is_delete, :response_id, up_file_attributes: [:format]))
    #@newresponses.build.up_file
    #@newupfiles = UpFile.new
    @responses = Response.where(thre_id: params[:id])
    #@upfiles = UpFile.where(thre_id: params[:id])
  end

  #def new
  #  @newresponses = Response.new
  #  @newresponses.up_file.build
  #end

  def delete
    @thres = Thre.find(params[:id])
    @thres.destroy
    #redirect_to action: :show, id:thre_id
    redirect_to top_show_path(id: @thres.board_id)
  end

  def create_res
    @responses = Response.new(params[:response].permit(:id, :thre_id, :content, :user_id, :user_name, :is_delete, :response_id))
    #@upfiles = UpFile.new(params[:response].permit(:format))
    #@upfiles = UpFile.new
    if user_signed_in? == true && @responses.user_name == "" then
      @responses.user_id = current_user.id
      @responses.user_name = current_user.name
    elsif user_signed_in? == true then
      @responses.user_id = current_user.id
    elsif user_signed_in? == false && @responses.user_name == "" then
      @responses.user_id = ""
      @responses.user_name = "匿名"
    end

    if @responses.is_delete == nil then
      @responses.is_delete = false
    end
    is_saved = @responses.save
    #@upfiles.save
    redirect_to list_show_path(params[:response]['thre_id'])
  end

  def delete_res
    @responses = Response.find(params[:id])
    @responses.destroy
    #redirect_to action: :show, id:thre_id
    redirect_to list_show_path(id: @responses.thre_id)
    #redirect_to list_show_path
  end

end

app/helpers/list_helper.rb
module ListHelper
end

app/views/list/create.html.slim
h1 List#create
p Find me in app/views/list/create.html.slim

app/views/list/show.html.slim
h1= @thres.name
- @responses.each_with_index do |response , idx|
  p
    = idx + 1
    | . 投稿者:
    = response.user_name
    - if user_signed_in? && response.user_id == current_user.id then
      = link_to '[削除]', list_delete_res_path(response.id), method: :delete, data: {confirm: "削除してもよろしいですか？"}
  p
    = response.content
  p
    /- if response.up_file_id != "" then
    /    = image_tag(response.up_file_id_url)
    /- else
    /    = response.content
    /- if response.up_file_id != "" then
    /  - up_file_id = response.up_file_id
    /  - user_id = response.user_id
    /  - unless @upfiles.blank?
    /    - @upfiles.each do |file|
    /    - if file.id == up_file_id then
    /      = image_tag(file.format_url)



h3
  | 投稿
= form_for @newresponses, :url => list_create_res_path do |f|
  p
  | お名前
  = f.text_field :user_name
  p
  = f.text_area :content

  /= f.fields_for, :up_file |g|
  /= f.file_field :up_file_id, id: :response_up_file_id
  p
  = f.hidden_field :thre_id
  = f.submit
  P
/= fields_for @newupfiles || @newupfiles.new, :url => list_create_res_path do |g|


= link_to 'Back', top_show_path(id: @thres.board_id)