config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
  :registrations => 'users/registrations',
  :sessions => 'users/sessions'
}

devise_scope :user do
  root 'top#index'
  get "sign_in", :to => "users/sessions#new"
  get "sign_out", :to => "users/sessions#destroy"
  end

  get 'pages/show', to: 'pages#index'
  get 'top', to: 'top#index', as: :top
  get 'top/edit', to: 'top#edit', as: :top_edit
  post 'top/create', to: 'top#create', as: :top_create
  get 'top/list/:id', to: 'top#show', as: :top_show
  delete 'top/delete/:id', to: 'top#delete', as: :top_delete
  post 'list/create', to: 'list#create', as: :list_create
  get 'res/:id', to: 'list#show', as: :list_show
  delete 'list/:id/delete', to: 'list#delete', as: :list_delete
  post 'res/create', to: 'list#create_res', as: :list_create_res
  delete 'res/:id/delete/:id', to: 'list#delete_res', as: :list_delete_res
  #get 'top/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Prototype
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    header
      .logo 
        img alt="LOGO" src="../../assets/logo.png" width="500"/
      nav
        ul
          .global-nav
              li
                - if user_signed_in?
                  strong
                    = link_to current_user.name, pages_show_path
                  = link_to 'プロフィール変更', edit_user_registration_path
                  = link_to 'ログアウト', destroy_user_session_path, method: :delete
                - else
                  = link_to 'サインアップ', new_user_registration_path
                  = link_to 'ログイン', new_user_session_path
    p.notice
      = notice
    p.alert
      = alert
    = yield